import {
  ContactIcon,
  LanguageIcon,
  LocationIcon,
  LogoutIcon,
  ProfileIcon,
  SubscriptionHistoryIcon,
} from "@/assets/icons";
import { ProfileItem } from "@/types";
import { QR_VALIDITY_DURATION_TYPE } from "./enums";
import { Colors } from "./theme";

export const OFFERS = [
  {
    id: 1,
    title: "Free Premium Shipping",
    description: "Rate your delivery experience and get 20% off next month",
    image: require("@/assets/images/offer.jpg"),
    buttonText: "Claim Offer",
    buttonColor: "#11A543",
  },
  {
    id: 2,
    title: "Free Premium Shipping",
    description: "Rate your delivery experience and get 20% off next month",
    image: require("@/assets/images/offer.jpg"),
    buttonText: "Claim Offer",
    buttonColor: "#11A543",
  },
];

export const QR_CODE_HISTORY = [
  {
    id: 1,
    title: "Entrance Gate QR",
    isActive: true,
    createdAt: new Date("2025-01-10T10:15:00Z").toISOString(),
    validityDuration: 15,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.MIN,
    maxUsers: 20,
    usersLeft: 10,
  },
  {
    id: 2,
    title: "Cafeteria Access",
    isActive: false,
    createdAt: new Date("2025-01-02T09:00:00Z").toISOString(),
    validityDuration: 2,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.HOUR,
    maxUsers: 50,
    usersLeft: 20,
  },
  {
    id: 3,
    title: "Conference Room QR",
    isActive: true,
    createdAt: new Date("2025-01-11T14:45:00Z").toISOString(),
    validityDuration: 1,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.DAY,
    maxUsers: 5,
    usersLeft: 2,
  },
  {
    id: 4,
    title: "Event Guest Entry",
    isActive: true,
    createdAt: new Date("2025-01-12T18:30:00Z").toISOString(),
    validityDuration: 30,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.MIN,
    maxUsers: 200,
    usersLeft: 90,
  },
  {
    id: 5,
    title: "VIP Lounge Access",
    isActive: false,
    createdAt: new Date("2025-01-05T11:20:00Z").toISOString(),
    validityDuration: 12,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.HOUR,
    maxUsers: 10,
    usersLeft: 0,
  },
  {
    id: 6,
    title: "Parking Zone QR",
    isActive: true,
    createdAt: new Date("2025-01-09T07:10:00Z").toISOString(),
    validityDuration: 2,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.DAY,
    maxUsers: 300,
    usersLeft: 100,
  },
  {
    id: 7,
    title: "Temporary Office QR",
    isActive: true,
    createdAt: new Date("2025-01-12T09:40:00Z").toISOString(),
    validityDuration: 45,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.MIN,
    maxUsers: 3,
    usersLeft: 2,
  },
  {
    id: 8,
    title: "Employee Training Session",
    isActive: false,
    createdAt: new Date("2025-01-01T13:00:00Z").toISOString(),
    validityDuration: 24,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.HOUR,
    maxUsers: 50,
    usersLeft: 10,
  },
];

export const SUBSCRIPTION_HISTORY = [
  {
    id: 1,
    title: "Standard Subscription Plan",
    startDate: new Date("2025-01-10T10:15:00Z").toISOString(),
    endDate: new Date("2025-02-10T10:15:00Z").toISOString(),
    transactionId: "TXN-001",
    paymentMethod: "Apple Pay",
    amount: "150",
    currency: "SAR",
  },
  {
    id: 2,
    title: "Premium Subscription Plan",
    startDate: new Date("2025-02-12T14:30:00Z").toISOString(),
    endDate: new Date("2025-03-12T14:30:00Z").toISOString(),
    transactionId: "TXN-002",
    paymentMethod: "Credit Card",
    amount: "250",
    currency: "SAR",
  },
  {
    id: 3,
    title: "Basic Subscription Plan",
    startDate: new Date("2025-03-05T09:45:00Z").toISOString(),
    endDate: new Date("2025-04-05T09:45:00Z").toISOString(),
    transactionId: "TXN-003",
    paymentMethod: "Mada",
    amount: "99",
    currency: "SAR",
  },
  {
    id: 4,
    title: "Standard Subscription Plan",
    startDate: new Date("2025-04-01T11:20:00Z").toISOString(),
    endDate: new Date("2025-05-01T11:20:00Z").toISOString(),
    transactionId: "TXN-004",
    paymentMethod: "Apple Pay",
    amount: "150",
    currency: "SAR",
  },
  {
    id: 5,
    title: "Premium Subscription Plan",
    startDate: new Date("2025-05-15T08:10:00Z").toISOString(),
    endDate: new Date("2025-06-15T08:10:00Z").toISOString(),
    transactionId: "TXN-005",
    paymentMethod: "Credit Card",
    amount: "250",
    currency: "SAR",
  },
  {
    id: 6,
    title: "Basic Subscription Plan",
    startDate: new Date("2025-06-20T17:50:00Z").toISOString(),
    endDate: new Date("2025-07-20T17:50:00Z").toISOString(),
    transactionId: "TXN-006",
    paymentMethod: "Mada",
    amount: "99",
    currency: "SAR",
  },
  {
    id: 7,
    title: "Standard Subscription Plan",
    startDate: new Date("2025-07-10T13:15:00Z").toISOString(),
    endDate: new Date("2025-08-10T13:15:00Z").toISOString(),
    transactionId: "TXN-007",
    paymentMethod: "Apple Pay",
    amount: "150",
    currency: "SAR",
  },
  {
    id: 8,
    title: "Premium Subscription Plan",
    startDate: new Date("2025-08-03T19:30:00Z").toISOString(),
    endDate: new Date("2025-09-03T19:30:00Z").toISOString(),
    transactionId: "TXN-008",
    paymentMethod: "Credit Card",
    amount: "250",
    currency: "SAR",
  },
  {
    id: 9,
    title: "Basic Subscription Plan",
    startDate: new Date("2025-09-25T06:40:00Z").toISOString(),
    endDate: new Date("2025-10-25T06:40:00Z").toISOString(),
    transactionId: "TXN-009",
    paymentMethod: "Mada",
    amount: "99",
    currency: "SAR",
  },
  {
    id: 10,
    title: "Standard Subscription Plan",
    startDate: new Date("2025-10-12T15:55:00Z").toISOString(),
    endDate: new Date("2025-11-12T15:55:00Z").toISOString(),
    transactionId: "TXN-010",
    paymentMethod: "Apple Pay",
    amount: "150",
    currency: "SAR",
  },
];

export const QR_SCAN_HISTORY = [
  {
    id: 1,
    qrCodeId: 1,
    qrCodeScanTime: new Date("2025-01-10T10:15:00Z").toISOString(),
    qrCodeScanLocation: "Entrance Gate",
    qrCodeScanUser: "John Doe",
    openedAt: new Date("2025-01-10T10:15:00Z").toISOString(),
    closedAt: new Date("2025-01-10T10:15:30Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 2,
    qrCodeId: 3,
    qrCodeScanTime: new Date("2025-01-11T14:22:00Z").toISOString(),
    qrCodeScanLocation: "Main Lobby",
    qrCodeScanUser: "Sarah Johnson",
    openedAt: new Date("2025-01-11T14:22:00Z").toISOString(),
    closedAt: new Date("2025-01-11T14:22:45Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=9bZkp7q19f0",
  },
  {
    id: 3,
    qrCodeId: 2,
    qrCodeScanTime: new Date("2025-01-12T09:45:00Z").toISOString(),
    qrCodeScanLocation: "Parking Area B",
    qrCodeScanUser: "Michael Chen",
    openedAt: new Date("2025-01-12T09:45:00Z").toISOString(),
    closedAt: new Date("2025-01-12T09:45:20Z").toISOString(),
    status: "failed",
    videoUrl: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
  },
  {
    id: 4,
    qrCodeId: 5,
    qrCodeScanTime: new Date("2025-01-13T16:30:00Z").toISOString(),
    qrCodeScanLocation: "Conference Room A",
    qrCodeScanUser: "Emily Rodriguez",
    openedAt: new Date("2025-01-13T16:30:00Z").toISOString(),
    closedAt: new Date("2025-01-13T16:31:15Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=3JZ_D3ELwOQ",
  },
  {
    id: 5,
    qrCodeId: 1,
    qrCodeScanTime: new Date("2025-01-14T08:00:00Z").toISOString(),
    qrCodeScanLocation: "Side Exit",
    qrCodeScanUser: "David Kim",
    openedAt: new Date("2025-01-14T08:00:00Z").toISOString(),
    closedAt: new Date("2025-01-14T08:00:35Z").toISOString(),
    status: "failed",
    videoUrl: "https://www.youtube.com/watch?v=hT_nvWreIhg",
  },
  {
    id: 6,
    qrCodeId: 7,
    qrCodeScanTime: new Date("2025-01-15T11:20:00Z").toISOString(),
    qrCodeScanLocation: "Warehouse Door 3",
    qrCodeScanUser: "Lisa Anderson",
    openedAt: new Date("2025-01-15T11:20:00Z").toISOString(),
    closedAt: new Date("2025-01-15T11:20:50Z").toISOString(),
    status: "Pending",
    videoUrl: "https://www.youtube.com/watch?v=M7lc1UVf-VE",
  },
  {
    id: 7,
    qrCodeId: 4,
    qrCodeScanTime: new Date("2025-01-16T13:45:00Z").toISOString(),
    qrCodeScanLocation: "Entrance Gate",
    qrCodeScanUser: "James Wilson",
    openedAt: new Date("2025-01-16T13:45:00Z").toISOString(),
    closedAt: new Date("2025-01-16T13:45:25Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=ZbZSe6N_BXs",
  },
  {
    id: 8,
    qrCodeId: 6,
    qrCodeScanTime: new Date("2025-01-17T15:10:00Z").toISOString(),
    qrCodeScanLocation: "Loading Dock",
    qrCodeScanUser: "Maria Garcia",
    openedAt: new Date("2025-01-17T15:10:00Z").toISOString(),
    closedAt: new Date("2025-01-17T15:10:40Z").toISOString(),
    status: "failed",
    videoUrl: "https://www.youtube.com/watch?v=fJ9rUzIMcZQ",
  },
  {
    id: 9,
    qrCodeId: 3,
    qrCodeScanTime: new Date("2025-01-18T07:30:00Z").toISOString(),
    qrCodeScanLocation: "Reception Area",
    qrCodeScanUser: "Robert Taylor",
    openedAt: new Date("2025-01-18T07:30:00Z").toISOString(),
    closedAt: new Date("2025-01-18T07:31:00Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=lXMskKTw3Bc",
  },
  {
    id: 10,
    qrCodeId: 8,
    qrCodeScanTime: new Date("2025-01-19T12:00:00Z").toISOString(),
    qrCodeScanLocation: "Emergency Exit",
    qrCodeScanUser: "Jennifer Lee",
    openedAt: new Date("2025-01-19T12:00:00Z").toISOString(),
    closedAt: new Date("2025-01-19T12:00:55Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=kXYiU_JCYtU",
  },
  {
    id: 11,
    qrCodeId: 2,
    qrCodeScanTime: new Date("2025-01-20T09:15:00Z").toISOString(),
    qrCodeScanLocation: "Office Building B",
    qrCodeScanUser: "William Brown",
    openedAt: new Date("2025-01-20T09:15:00Z").toISOString(),
    closedAt: new Date("2025-01-20T09:15:30Z").toISOString(),
    status: "Pending",
    videoUrl: "https://www.youtube.com/watch?v=SlPhMPnQ58k",
  },
  {
    id: 12,
    qrCodeId: 9,
    qrCodeScanTime: new Date("2025-01-21T17:25:00Z").toISOString(),
    qrCodeScanLocation: "Cafeteria Entrance",
    qrCodeScanUser: "Amanda Martinez",
    openedAt: new Date("2025-01-21T17:25:00Z").toISOString(),
    closedAt: new Date("2025-01-21T17:25:45Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=OPf0YbXqDm0",
  },
];

export const STATUS_CARDS_DATA = [
  {
    id: "1",
    icon: "online-prediction",
    title: "QBox Status",
    statusText: "Online",
    statusColor: Colors.success,
  },
  {
    id: "2",
    icon: "camera-alt",
    title: "Camera",
    statusText: "Working",
    statusColor: Colors.success,
  },
  {
    id: "3",
    icon: "lightbulb-outline",
    title: "LED Indicator",
    statusText: "Red",
    statusColor: Colors.danger,
  },
  {
    id: "4",
    icon: "power",
    title: "Power Status",
    statusText: "Plugged",
    statusColor: Colors.primary,
  },
];

export const MENU_ITEM: ProfileItem[] = [
  {
    id: 1,
    icon: ProfileIcon,
    title: "Basic Information",
    path: "/basicInformation",
  },
  {
    id: 2,
    icon: LanguageIcon,
    title: "Language",
    path: "/appLanguage",
    rightText: "English",
  },
  {
    id: 3,
    icon: LocationIcon,
    title: "My QBox Location",
    path: "/myQBoxLocation",
  },
  {
    id: 4,
    icon: SubscriptionHistoryIcon,
    title: "Subscription History",
    path: "/subscriptionHistory",
  },
  { id: 5, icon: ContactIcon, title: "Contact Us", path: "/" },
  {
    id: 6,
    icon: LogoutIcon,
    title: "Logout",
    backgroundColor: Colors.lightRed,
    textColor: Colors.danger,
  },
];
