import {
  CameraIcon,
  ContactIcon,
  LanguageIcon,
  LED_IndicatorIcon,
  LocationIcon,
  LogoutIcon,
  OnlineStatusIcon,
  PackageTypeIcon,
  PackageValueIcon,
  PackageWeightIcon,
  PowerStatusIcom,
  ProfileIcon,
  SubscriptionHistoryIcon,
} from "@/assets/icons";
import { PackageDetailsType, ProfileItem } from "@/types";
import { PACKAGE_TYPE, QR_VALIDITY_DURATION_TYPE } from "./enums";
import { Colors } from "./theme";

export const OFFERS = [
  {
    id: 1,
    title: "Free Premium Shipping",
    description: "Rate your delivery experience and get 20% off next month",
    image: require("@/assets/images/offer.jpg"),
    buttonText: "Claim Offer",
    buttonColor: "#11A543",
  },
  {
    id: 2,
    title: "Free Premium Shipping",
    description: "Rate your delivery experience and get 20% off next month",
    image: require("@/assets/images/offer.jpg"),
    buttonText: "Claim Offer",
    buttonColor: "#11A543",
  },
];

export const QR_CODE_HISTORY = [
  {
    id: 1,
    title: "Entrance Gate QR",
    isActive: true,
    createdAt: new Date("2025-01-10T10:15:00Z").toISOString(),
    validityDuration: 15,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.MIN,
    maxUsers: 20,
    usersLeft: 10,
  },
  {
    id: 2,
    title: "Cafeteria Access",
    isActive: false,
    createdAt: new Date("2025-01-02T09:00:00Z").toISOString(),
    validityDuration: 2,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.HOUR,
    maxUsers: 50,
    usersLeft: 20,
  },
  {
    id: 3,
    title: "Conference Room QR",
    isActive: true,
    createdAt: new Date("2025-01-11T14:45:00Z").toISOString(),
    validityDuration: 1,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.DAY,
    maxUsers: 5,
    usersLeft: 2,
  },
  {
    id: 4,
    title: "Event Guest Entry",
    isActive: true,
    createdAt: new Date("2025-01-12T18:30:00Z").toISOString(),
    validityDuration: 30,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.MIN,
    maxUsers: 200,
    usersLeft: 90,
  },
  {
    id: 5,
    title: "VIP Lounge Access",
    isActive: false,
    createdAt: new Date("2025-01-05T11:20:00Z").toISOString(),
    validityDuration: 12,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.HOUR,
    maxUsers: 10,
    usersLeft: 0,
  },
  {
    id: 6,
    title: "Parking Zone QR",
    isActive: true,
    createdAt: new Date("2025-01-09T07:10:00Z").toISOString(),
    validityDuration: 2,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.DAY,
    maxUsers: 300,
    usersLeft: 100,
  },
  {
    id: 7,
    title: "Temporary Office QR",
    isActive: true,
    createdAt: new Date("2025-01-12T09:40:00Z").toISOString(),
    validityDuration: 45,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.MIN,
    maxUsers: 3,
    usersLeft: 2,
  },
  {
    id: 8,
    title: "Employee Training Session",
    isActive: false,
    createdAt: new Date("2025-01-01T13:00:00Z").toISOString(),
    validityDuration: 24,
    validityDurationType: QR_VALIDITY_DURATION_TYPE.HOUR,
    maxUsers: 50,
    usersLeft: 10,
  },
];

export const SUBSCRIPTION_HISTORY = [
  {
    id: 1,
    title: "Standard Subscription Plan",
    startDate: new Date("2025-01-10T10:15:00Z").toISOString(),
    endDate: new Date("2025-02-10T10:15:00Z").toISOString(),
    transactionId: "TXN-001",
    paymentMethod: "Apple Pay",
    amount: "150",
    currency: "SAR",
  },
  {
    id: 2,
    title: "Premium Subscription Plan",
    startDate: new Date("2025-02-12T14:30:00Z").toISOString(),
    endDate: new Date("2025-03-12T14:30:00Z").toISOString(),
    transactionId: "TXN-002",
    paymentMethod: "Credit Card",
    amount: "250",
    currency: "SAR",
  },
  {
    id: 3,
    title: "Basic Subscription Plan",
    startDate: new Date("2025-03-05T09:45:00Z").toISOString(),
    endDate: new Date("2025-04-05T09:45:00Z").toISOString(),
    transactionId: "TXN-003",
    paymentMethod: "Mada",
    amount: "99",
    currency: "SAR",
  },
  {
    id: 4,
    title: "Standard Subscription Plan",
    startDate: new Date("2025-04-01T11:20:00Z").toISOString(),
    endDate: new Date("2025-05-01T11:20:00Z").toISOString(),
    transactionId: "TXN-004",
    paymentMethod: "Apple Pay",
    amount: "150",
    currency: "SAR",
  },
  {
    id: 5,
    title: "Premium Subscription Plan",
    startDate: new Date("2025-05-15T08:10:00Z").toISOString(),
    endDate: new Date("2025-06-15T08:10:00Z").toISOString(),
    transactionId: "TXN-005",
    paymentMethod: "Credit Card",
    amount: "250",
    currency: "SAR",
  },
  {
    id: 6,
    title: "Basic Subscription Plan",
    startDate: new Date("2025-06-20T17:50:00Z").toISOString(),
    endDate: new Date("2025-07-20T17:50:00Z").toISOString(),
    transactionId: "TXN-006",
    paymentMethod: "Mada",
    amount: "99",
    currency: "SAR",
  },
  {
    id: 7,
    title: "Standard Subscription Plan",
    startDate: new Date("2025-07-10T13:15:00Z").toISOString(),
    endDate: new Date("2025-08-10T13:15:00Z").toISOString(),
    transactionId: "TXN-007",
    paymentMethod: "Apple Pay",
    amount: "150",
    currency: "SAR",
  },
  {
    id: 8,
    title: "Premium Subscription Plan",
    startDate: new Date("2025-08-03T19:30:00Z").toISOString(),
    endDate: new Date("2025-09-03T19:30:00Z").toISOString(),
    transactionId: "TXN-008",
    paymentMethod: "Credit Card",
    amount: "250",
    currency: "SAR",
  },
  {
    id: 9,
    title: "Basic Subscription Plan",
    startDate: new Date("2025-09-25T06:40:00Z").toISOString(),
    endDate: new Date("2025-10-25T06:40:00Z").toISOString(),
    transactionId: "TXN-009",
    paymentMethod: "Mada",
    amount: "99",
    currency: "SAR",
  },
  {
    id: 10,
    title: "Standard Subscription Plan",
    startDate: new Date("2025-10-12T15:55:00Z").toISOString(),
    endDate: new Date("2025-11-12T15:55:00Z").toISOString(),
    transactionId: "TXN-010",
    paymentMethod: "Apple Pay",
    amount: "150",
    currency: "SAR",
  },
];

export const QR_SCAN_HISTORY = [
  {
    id: 1,
    qrCodeId: 1,
    qrCodeScanTime: new Date("2025-01-10T10:15:00Z").toISOString(),
    qrCodeScanLocation: "Entrance Gate",
    qrCodeScanUser: "John Doe",
    openedAt: new Date("2025-01-10T10:15:00Z").toISOString(),
    closedAt: new Date("2025-01-10T10:15:30Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 2,
    qrCodeId: 3,
    qrCodeScanTime: new Date("2025-01-11T14:22:00Z").toISOString(),
    qrCodeScanLocation: "Main Lobby",
    qrCodeScanUser: "Sarah Johnson",
    openedAt: new Date("2025-01-11T14:22:00Z").toISOString(),
    closedAt: new Date("2025-01-11T14:22:45Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=9bZkp7q19f0",
  },
  {
    id: 3,
    qrCodeId: 2,
    qrCodeScanTime: new Date("2025-01-12T09:45:00Z").toISOString(),
    qrCodeScanLocation: "Parking Area B",
    qrCodeScanUser: "Michael Chen",
    openedAt: new Date("2025-01-12T09:45:00Z").toISOString(),
    closedAt: new Date("2025-01-12T09:45:20Z").toISOString(),
    status: "failed",
    videoUrl: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
  },
  {
    id: 4,
    qrCodeId: 5,
    qrCodeScanTime: new Date("2025-01-13T16:30:00Z").toISOString(),
    qrCodeScanLocation: "Conference Room A",
    qrCodeScanUser: "Emily Rodriguez",
    openedAt: new Date("2025-01-13T16:30:00Z").toISOString(),
    closedAt: new Date("2025-01-13T16:31:15Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=3JZ_D3ELwOQ",
  },
  {
    id: 5,
    qrCodeId: 1,
    qrCodeScanTime: new Date("2025-01-14T08:00:00Z").toISOString(),
    qrCodeScanLocation: "Side Exit",
    qrCodeScanUser: "David Kim",
    openedAt: new Date("2025-01-14T08:00:00Z").toISOString(),
    closedAt: new Date("2025-01-14T08:00:35Z").toISOString(),
    status: "failed",
    videoUrl: "https://www.youtube.com/watch?v=hT_nvWreIhg",
  },
  {
    id: 6,
    qrCodeId: 7,
    qrCodeScanTime: new Date("2025-01-15T11:20:00Z").toISOString(),
    qrCodeScanLocation: "Warehouse Door 3",
    qrCodeScanUser: "Lisa Anderson",
    openedAt: new Date("2025-01-15T11:20:00Z").toISOString(),
    closedAt: new Date("2025-01-15T11:20:50Z").toISOString(),
    status: "Pending",
    videoUrl: "https://www.youtube.com/watch?v=M7lc1UVf-VE",
  },
  {
    id: 7,
    qrCodeId: 4,
    qrCodeScanTime: new Date("2025-01-16T13:45:00Z").toISOString(),
    qrCodeScanLocation: "Entrance Gate",
    qrCodeScanUser: "James Wilson",
    openedAt: new Date("2025-01-16T13:45:00Z").toISOString(),
    closedAt: new Date("2025-01-16T13:45:25Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=ZbZSe6N_BXs",
  },
  {
    id: 8,
    qrCodeId: 6,
    qrCodeScanTime: new Date("2025-01-17T15:10:00Z").toISOString(),
    qrCodeScanLocation: "Loading Dock",
    qrCodeScanUser: "Maria Garcia",
    openedAt: new Date("2025-01-17T15:10:00Z").toISOString(),
    closedAt: new Date("2025-01-17T15:10:40Z").toISOString(),
    status: "failed",
    videoUrl: "https://www.youtube.com/watch?v=fJ9rUzIMcZQ",
  },
  {
    id: 9,
    qrCodeId: 3,
    qrCodeScanTime: new Date("2025-01-18T07:30:00Z").toISOString(),
    qrCodeScanLocation: "Reception Area",
    qrCodeScanUser: "Robert Taylor",
    openedAt: new Date("2025-01-18T07:30:00Z").toISOString(),
    closedAt: new Date("2025-01-18T07:31:00Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=lXMskKTw3Bc",
  },
  {
    id: 10,
    qrCodeId: 8,
    qrCodeScanTime: new Date("2025-01-19T12:00:00Z").toISOString(),
    qrCodeScanLocation: "Emergency Exit",
    qrCodeScanUser: "Jennifer Lee",
    openedAt: new Date("2025-01-19T12:00:00Z").toISOString(),
    closedAt: new Date("2025-01-19T12:00:55Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=kXYiU_JCYtU",
  },
  {
    id: 11,
    qrCodeId: 2,
    qrCodeScanTime: new Date("2025-01-20T09:15:00Z").toISOString(),
    qrCodeScanLocation: "Office Building B",
    qrCodeScanUser: "William Brown",
    openedAt: new Date("2025-01-20T09:15:00Z").toISOString(),
    closedAt: new Date("2025-01-20T09:15:30Z").toISOString(),
    status: "Pending",
    videoUrl: "https://www.youtube.com/watch?v=SlPhMPnQ58k",
  },
  {
    id: 12,
    qrCodeId: 9,
    qrCodeScanTime: new Date("2025-01-21T17:25:00Z").toISOString(),
    qrCodeScanLocation: "Cafeteria Entrance",
    qrCodeScanUser: "Amanda Martinez",
    openedAt: new Date("2025-01-21T17:25:00Z").toISOString(),
    closedAt: new Date("2025-01-21T17:25:45Z").toISOString(),
    status: "success",
    videoUrl: "https://www.youtube.com/watch?v=OPf0YbXqDm0",
  },
];

export const STATUS_CARDS_DATA = [
  {
    id: "1",
    icon: OnlineStatusIcon,
    title: "QBox Status",
    statusText: "Online",
    statusColor: Colors.success,
  },
  {
    id: "2",
    icon: CameraIcon,
    title: "Camera",
    statusText: "Working",
    statusColor: Colors.success,
  },
  {
    id: "3",
    icon: LED_IndicatorIcon,
    title: "LED Indicator",
    statusText: "Red",
    statusColor: Colors.danger,
  },
  {
    id: "4",
    icon: PowerStatusIcom,
    title: "Power Status",
    statusText: "Plugged",
    statusColor: Colors.primary,
  },
];

export const PACKAGE_ATTRIBUTE_DATA = [
  {
    id: "1",
    icon: PackageTypeIcon,
    title: "Package Type",
    statusText: "Electronics",
  },
  {
    id: "2",
    icon: PackageValueIcon,
    title: "Item Value",
    statusText: "250",
  },
  {
    id: "3",
    icon: PackageWeightIcon,
    title: "Package Weight",
    statusText: "1 kg",
  },
];

export const MENU_ITEM: ProfileItem[] = [
  {
    id: 1,
    icon: ProfileIcon,
    title: "Basic Information",
    path: "/basicInformation",
  },
  {
    id: 2,
    icon: LanguageIcon,
    title: "Language",
    path: "/appLanguage",
    rightText: "English",
  },
  {
    id: 3,
    icon: LocationIcon,
    title: "My QBox Location",
    path: "/myQBoxLocation",
  },
  {
    id: 4,
    icon: SubscriptionHistoryIcon,
    title: "Subscription History",
    path: "/subscriptionHistory",
  },
  { id: 5, icon: ContactIcon, title: "Contact Us", path: "/" },
  {
    id: 6,
    icon: LogoutIcon,
    title: "Logout",
    backgroundColor: Colors.lightRed,
    textColor: Colors.danger,
  },
];
export const PACKAGES = [
  // INCOMING
  {
    id: 1,
    title: "Courier Name",
    Subtitle: "Ali Khan / Ahmed Raza",
    trackingId: "SM240815001",
    createdAt: new Date("2025-01-19T12:00:00Z").toISOString(),
    city: "Lahore",
    status: null,
    type: PACKAGE_TYPE.INCOMING,
  },
  {
    id: 2,
    title: "FastEx Logistics",
    Subtitle: "Driver: Umar / Sender: Bilal",
    trackingId: "SM240815002",
    createdAt: new Date("2025-01-20T09:30:00Z").toISOString(),
    city: "Karachi",
    status: null,
    type: PACKAGE_TYPE.INCOMING,
  },

  // OUTGOING
  {
    id: 3,
    title: "ParcelPro",
    Subtitle: "Express Delivery",
    trackingId: "SM240815003",
    createdAt: new Date("2025-01-18T15:45:00Z").toISOString(),
    city: null,
    status: "Send",
    type: PACKAGE_TYPE.OUTGOING,
  },
  {
    id: 4,
    title: "SpeedyShip",
    Subtitle: "Premium Delivery",
    trackingId: "SM240815004",
    createdAt: new Date("2025-01-17T11:00:00Z").toISOString(),
    city: null,
    status: "Return",
    type: PACKAGE_TYPE.OUTGOING,
  },

  // DELIVERED
  {
    id: 5,
    title: "BlueLine Couriers",
    Subtitle: "Delivered by: Hassan",
    trackingId: "SM240815005",
    createdAt: new Date("2025-01-16T08:10:00Z").toISOString(),
    city: null,
    status: null,
    type: PACKAGE_TYPE.DELIVERED,
  },
  {
    id: 6,
    title: "FlyPost Service",
    Subtitle: "Sender: Zain",
    trackingId: "SM240815006",
    createdAt: new Date("2025-01-14T14:20:00Z").toISOString(),
    city: null,
    status: null,
    type: PACKAGE_TYPE.DELIVERED,
  },
];

// Add these new constants to your existing appData.ts file

// Package timeline/history data
export const PACKAGE_TIMELINE = [
  {
    id: 1,
    packageId: 1,
    timestamp: new Date("2021-03-10T20:01:00Z").toISOString(),
    status: "Issue Logged",
    location: "Riyadh",
  },
  {
    id: 2,
    packageId: 1,
    timestamp: new Date("2021-03-08T20:01:00Z").toISOString(),
    status: "Delivery Completed",
    location: "Riyadh",
  },
  {
    id: 3,
    packageId: 1,
    timestamp: new Date("2021-03-10T20:01:00Z").toISOString(),
    status: "Notification Sent to Homeowner",
    location: "Riyadh",
  },
  {
    id: 4,
    packageId: 1,
    timestamp: new Date("2021-03-08T20:01:00Z").toISOString(),
    status: "Locker Closed",
    location: "Riyadh",
  },
  {
    id: 5,
    packageId: 1,
    timestamp: new Date("2021-03-07T12:27:00Z").toISOString(),
    status: "Locker Opened",
    location: "Riyadh",
  },
  {
    id: 6,
    packageId: 1,
    timestamp: new Date("2021-03-10T11:43:00Z").toISOString(),
    status: "QR Scanned by Driver",
    location: "Riyadh",
  },
  {
    id: 7,
    packageId: 1,
    timestamp: new Date("2021-03-03T10:48:00Z").toISOString(),
    status: "Out for Delivery",
    location: "Jeddah",
  },
  {
    id: 8,
    packageId: 1,
    timestamp: new Date("2021-02-24T23:17:00Z").toISOString(),
    status: "Shipment Created",
    location: "Asr",
  },
  // Package 2 timeline
  {
    id: 9,
    packageId: 2,
    timestamp: new Date("2025-01-20T14:30:00Z").toISOString(),
    status: "Delivered",
    location: "Karachi",
  },
  {
    id: 10,
    packageId: 2,
    timestamp: new Date("2025-01-20T12:15:00Z").toISOString(),
    status: "Out for Delivery",
    location: "Karachi",
  },
  {
    id: 11,
    packageId: 2,
    timestamp: new Date("2025-01-20T09:30:00Z").toISOString(),
    status: "Arrived at Hub",
    location: "Karachi",
  },
  // Package 3 timeline
  {
    id: 12,
    packageId: 3,
    timestamp: new Date("2025-01-18T18:00:00Z").toISOString(),
    status: "Package Sent",
    location: "Lahore",
  },
  {
    id: 13,
    packageId: 3,
    timestamp: new Date("2025-01-18T15:45:00Z").toISOString(),
    status: "QR Code Generated",
    location: "Lahore",
  },
];

// Package details with additional information
export const PACKAGE_DETAILS: PackageDetailsType[] = [
  // =================== ID: 1 (INCOMING) ===================
  {
    id: 1,
    type: PACKAGE_TYPE.INCOMING,
    courierName: "Courier Name",
    lastUpdate: new Date("2025-12-10T11:05:00Z").toISOString(),
    qrCode: "SB-kK_KD",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    imageUrl: require("@/assets/images/packageItem.jpg"),
    attributes: [
      { type: "Package Type", value: "Electronics" },
      { type: "Item Value", value: "250" },
      { type: "Package Weight", value: "1 kg" },
    ],
  },

  // =================== ID: 2 (INCOMING) ===================
  {
    id: 2,
    type: PACKAGE_TYPE.INCOMING,
    courierName: "FastEx Logistics",
    lastUpdate: new Date("2025-01-20T14:30:00Z").toISOString(),
    qrCode: "FE-2024-XY",
    description:
      "Express delivery package containing electronic accessories and gadgets. Packed with protective materials for safe transportation.",
    imageUrl: require("@/assets/images/packageItem.jpg"),
    attributes: [
      { type: "Package Type", value: "Electronics" },
      { type: "Item Value", value: "180" },
      { type: "Package Weight", value: "0.8 kg" },
    ],
  },

  // =================== ID: 3 (OUTGOING - Send) ===================
  {
    id: 3,
    type: PACKAGE_TYPE.OUTGOING,
    courierName: "ParcelPro",
    lastUpdate: new Date("2025-01-18T15:45:00Z").toISOString(),
    qrCode: "PP-EXP-03",
    status: "Send",
    phoneNumber: "033334444555",
    email: "test@gmail.com",
    recepientName: "Sardar",
    description:
      "Premium package with fragile items. Handle with care. Contains specialized equipment requiring careful handling.",
    imageUrl: require("@/assets/images/packageItem.jpg"),
    attributes: [
      { type: "Package Type", value: "Fragile" },
      { type: "Item Value", value: "420" },
      { type: "Package Weight", value: "1.5 kg" },
    ],
    paymentSummary: {
      paymentMethod: "Apple Pay",
      charges: [
        {
          key: "Base delivery fee (First 5 Kg’s)",
          value: 5,
        },
        {
          key: "Additional per Kg",
          value: 10,
        },
        {
          key: "Tax Fuel",
          value: 5,
        },
      ],
      currency: "SAR",
    },
  },

  // =================== ID: 4 (OUTGOING - Return) ===================
  {
    id: 4,
    type: PACKAGE_TYPE.OUTGOING,
    courierName: "SpeedyShip",
    lastUpdate: new Date("2025-01-17T11:00:00Z").toISOString(),
    qrCode: "SS-RET-04",
    status: "Return",
    phoneNumber: "033334444555",
    email: "test@gmail.com",
    recepientName: "Sardar",
    description:
      "Return package processed and scheduled for dispatch. Contains items returned by the user due to incorrect specifications.",
    imageUrl: require("@/assets/images/packageItem.jpg"),
    attributes: [
      { type: "Package Type", value: "Returned Item" },
      { type: "Item Value", value: "320" },
      { type: "Package Weight", value: "1.2 kg" },
    ],
  },

  // =================== ID: 5 (DELIVERED) ===================
  {
    id: 5,
    type: PACKAGE_TYPE.DELIVERED,
    courierName: "BlueLine Couriers",
    lastUpdate: new Date("2025-01-16T08:10:00Z").toISOString(),
    qrCode: "BL-DEL-05",
    description:
      "Package successfully delivered to the recipient. Verified and confirmed by the delivery personnel.",
    imageUrl: require("@/assets/images/packageItem.jpg"),
    attributes: [
      { type: "Package Type", value: "General Item" },
      { type: "Item Value", value: "150" },
      { type: "Package Weight", value: "0.9 kg" },
    ],
  },

  // =================== ID: 6 (DELIVERED) ===================
  {
    id: 6,
    type: PACKAGE_TYPE.DELIVERED,
    courierName: "FlyPost Service",
    lastUpdate: new Date("2025-01-14T14:20:00Z").toISOString(),
    qrCode: "FP-DEL-06",
    description:
      "Delivered package containing clothing items. No damages reported and delivery was on time.",
    imageUrl: require("@/assets/images/packageItem.jpg"),
    attributes: [
      { type: "Package Type", value: "Clothing" },
      { type: "Item Value", value: "95" },
      { type: "Package Weight", value: "0.6 kg" },
    ],
  },
];
