export type SendPackageFormValues = {
  fullName: string;
  email: string;
  phone: string;
  qBoxId: string;
  receiverHomeOwnerId: string;
  senderHomeOwnerId: string;
  serviceProviderId: string;
  packageType: string;
  packageWeight: number;
  currency: string;
  packageItemValue: number;
  packageDescription: string;
  qboxImage: string;
  shippingCompany: string;
  shippingCompanyName: string;
  paymentMethod: string;
  paymentMethodId: string;
  cardHolderName: string;
  cardNumber: string;
  expiry: string;
  cvv: string;
  charges: number;
};
